<!--
<?xml version="1.0" encoding="ISO-8859-1"?>
-->
<!DOCTYPE specialConfigs [
  <!ELEMENT specialConfigs (configuration*) >
  <!ELEMENT configuration (name, frontEnd, frequency+, sideband, mixers, mode, systems, species+, transition+, bandwidth+, shift+) >
  <!ELEMENT name (#PCDATA) >
  <!ELEMENT frontEnd (#PCDATA) >
  <!ELEMENT frequency (#PCDATA) >
  <!ELEMENT sideband (#PCDATA) >
  <!ELEMENT mixers (#PCDATA) >
  <!ELEMENT mode (#PCDATA) >
  <!ELEMENT systems (#PCDATA) >
  <!ELEMENT species (#PCDATA)>
  <!ELEMENT transition (#PCDATA)>
  <!ELEMENT bandwidth (#PCDATA)>
  <!ELEMENT shift (#PCDATA)>
]>


<specialConfigs>

<configuration>
  <name>      HARP_COH13CN_250</name>
  <frontEnd>  HARP            </frontEnd>
  <frequency> 0.              </frequency>
  <frequency> 0.              </frequency>
  <sideband>  LSB             </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <species>   CO              </species>
  <species>   H-13-CN         </species>
  <transition>3 - 2           </transition>
  <transition>4 - 3           </transition>
  <bandwidth> 250.0           </bandwidth>
  <bandwidth> 250.0           </bandwidth>
  <shift>     5.0E9           </shift>
  <shift>     5.45623E9       </shift>
</configuration>

<configuration>
  <name>      HARP_H2DN2H_250X2</name>
  <frontEnd>  HARP            </frontEnd>
  <frequency> 0.              </frequency>
  <frequency> 0.              </frequency>
  <sideband>  USB             </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <species>   H2D+            </species>
  <species>   N2H+            </species>
  <transition>1 1 0 0 - 1 1 1 0</transition>
  <transition>4 - 3           </transition>
  <bandwidth> 250.0           </bandwidth>
  <bandwidth> 250.0           </bandwidth>
  <shift>     5.0E9           </shift>
  <shift>     5.251169E9      </shift>
</configuration>

<configuration>
  <name>      HARP_13C18O_250x2</name>
  <frontEnd>  HARP            </frontEnd>
  <frequency> 0.              </frequency>
  <frequency> 0.              </frequency>
  <sideband>  LSB             </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <species>   C-18-O          </species>
  <species>   13-CO           </species>
  <transition>3 - 2           </transition>
  <transition>3 - 2           </transition>
  <bandwidth> 250.0           </bandwidth>
  <bandwidth> 250.0           </bandwidth>
  <shift>  5.607009925558312E9</shift>
  <shift>  4.349595125558289E9</shift>
</configuration>

<configuration>
  <name>      HARP_DCN_HNC_250x2</name>
  <frontEnd>  HARP            </frontEnd>
  <frequency> 0.              </frequency>
  <frequency> 0.              </frequency>
  <sideband>  BEST            </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <species>   DCN             </species>
  <species>   HNC             </species>
  <transition>5 - 4           </transition>
  <transition>4 - 3           </transition>
  <bandwidth> 250.0           </bandwidth>
  <bandwidth> 250.0           </bandwidth>
  <shift>  4.73E9             </shift>
  <shift>  5.3138188E9</shift>
</configuration>

<configuration>
  <name>      HARP_CO_H13CO_250x2</name>
  <frontEnd>  HARP            </frontEnd>
  <frequency> 0.              </frequency>
  <frequency> 0.              </frequency>
  <sideband>  BEST            </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <species>   CO              </species>
  <species>   H-13-CO+ v=0    </species>
  <transition>3 - 2           </transition>
  <transition>4 - 3           </transition>
  <bandwidth> 250.0           </bandwidth>
  <bandwidth> 250.0           </bandwidth>
  <shift>  4.43E9             </shift>
  <shift>  5.6325501E9        </shift>
</configuration>

<configuration>
  <name>      HARP_C170_C34S_250x2</name>
  <frontEnd>  HARP            </frontEnd>
  <frequency> 0.              </frequency>
  <frequency> 0.              </frequency>
  <sideband>  BEST            </sideband>
  <mixers>    1               </mixers>
  <mode>      SSB             </mode>
  <systems>   2               </systems>
  <species>   C-17-O          </species>
  <species>   C-34-S          </species>
  <transition>3 - 2           </transition>
  <transition>7 - 6           </transition>
  <bandwidth> 250.0           </bandwidth>
  <bandwidth> 250.0           </bandwidth>
  <shift>  5.0E9              </shift>
  <shift>  5.3355603E9        </shift>
</configuration>

</specialConfigs>

